In [1]:
import pandas as pd
import numpy as np
df=pd.read_csv('Lifestyle_questions_Corresponding_Disease_Latest - Sheet1.csv',encoding = "ISO-8859-1")
df.head()


R_No  hours_walk_in_a_day  walk_to_workplace  smoking  drinking_alchohol  \
0     1                    4                  1        3                  4   
1     1                    4                  2        3                  3   
2     1                    4                  1        3                  4   
3     1                    4                  2        3                  3   
4     1                    4                  1        3                  4   

   hours_sit  sit_straight  cushioned_chair_to_sit  sit_in_front_of_computer  \
0          3             1                       1                         1   
1          3             1                       1                         1   
2          4             1                       1                         1   
3          4             1                       1                         1   
4          3             1                       1                         1   

   walk_after_lunch_dinner  ...  stress_personal_life_work_life  \
0                        1  ...                               1   
1                        1  ...                               1   
2                        1  ...                               1   
3                        1  ...                               1   
4                        1  ...                               2   

   sit_in_traffic_jam  use_headphones_or_earphones_constantly  \
0                   3                                       3   
1                   4                                       3   
2                   5                                       4   
3                   3                                       4   
4                   4                                       5   

   drink_water_in_a_day  headache  depression  carry_heavy_weights  tiredness  \
0                     1         1           1                    2          2   
1                     1         1           2                    2          3   
2                     2         2           1                    2          2   
3                     2         2           2                    2          3   
4                     3         1           1                    2          2   

   limit_sugar_and-sallt_intake  lifestyle_disease  
0                             1     Mental illness  
1                             1     Mental illness  
2                             1     Mental illness  
3                             1     Mental illness  
4                             1     Mental illness  

[5 rows x 27 columns]

In [2]:
x = df.iloc[:, 1:26].values  
# print(x) 
y = df.iloc[:, 0].values
# print(y)
z = df.iloc[:, -1].values
s={}
y1=list(y)
z1=list(z)
for i in range(0, len(y1)):
    if(z1[i] not in s ):
        s[z1[i]]=y1[i]
print(s)


{'Mental illness': 1, 'Back Pain': 2, 'Stroke': 3, 'atherosclerosis': 4, 'Obesity': 5, 'Cirrhosis': 6, 'Cancer': 7, 'Heart Disease': 8, 'High Blood Pressure': 9, 'Type-II Diabetes': 10, "Alzheimer's disease": 11, 'Arthritis\r': 12, 'Athritis': 13, 'Atherosclerosis': 13, 'Asthma': 14, 'Chronic obstructive pulmonary disease,': 15, 'Metabolic syndrome': 16, 'Chronic renal failure ': 17, 'Osteoporosis': 18, 'Swimmerâ\x80\x99s ear': 19, 'Nephritis': 20, 'Eye Pain': 21}


In [3]:
from sklearn import datasets 
from sklearn.metrics import confusion_matrix 
from sklearn.model_selection import train_test_split 

  
# dividing X, y into train and test data 
X_train, X_test, y_train, y_test = train_test_split(x, y, random_state = 0) 
  
# training a KNN classifier 


In [4]:
from sklearn.neighbors import KNeighborsClassifier 
knn = KNeighborsClassifier(n_neighbors = 21).fit(X_train, y_train) 
  
# accuracy on X_test 
accuracy = knn.score(X_test, y_test) 
print(accuracy)
  
# creating a confusion matrix 
knn_predictions = knn.predict(X_test)  
cm = confusion_matrix(y_test, knn_predictions) 
print(cm)

0.37037037037037035
[[1 2 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 6 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0]
 [0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 2 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0]
 [0 0 0 0 0 2 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 2 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0]
 [0 1 0 0 1 0 0 0 0 0 0 0 0 1 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 1 0 1 0 0 0 0 0]
 [1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]]


In [5]:
from sklearn.ensemble import RandomForestClassifier

classifier = RandomForestClassifier(n_estimators=100, random_state=0)
classifier.fit(X_train, y_train)
y_pred = classifier.predict(X_test)
errors = abs(y_pred - y_test)


In [6]:
print('Metrics for Random Forest Trained on Original Data')
print('Average absolute error:', round(np.mean(errors), 2), 'degrees.')
# Calculate mean absolute percentage error (MAPE)
mape = 100 * (errors / y_test)
# Calculate and display accuracy
accuracy = 100 - np.mean(mape)
print('Accuracy:', round(accuracy, 2), '%.')
cm = confusion_matrix(y_test, y_pred) 
print(cm)

Metrics for Random Forest Trained on Original Data
Average absolute error: 1.59 degrees.
Accuracy: 80.19 %.
[[3 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 6 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 2 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 2 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 2 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0]
 [0 0 0 0 2 0 0 1 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 2 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1]]


In [7]:
print(y_pred)

[ 9  2 15  1  2 20 21  1  2  6 13  2  8 11 16  9  2 15  6  9 20  2  7 18
 13  1 13]


In [8]:
import pickle
filename = 'model2.sav'
pickle.dump(classifier, open(filename, 'wb'))